#!/bin/bash
SQL_HOME=~/sql

DHIS2_HOST=localhost
DHIS2_DB_PORT=5432
DHIS2_DB_USERNAME=dhis
DHIS2_DB_NAME=dhis2

COMMON_FUNCTIONS_SQL="common_functions.sql"
MENTAL_HEALTH_SQL="mental_health.sql"
MAIN_SQL="main.sql"

[ ! -d $SQL_HOME ] && mkdir $SQL_HOME

#echo $DHIS2_DB_USERNAME
#echo $DHIS2_HOST
#echo $DHIS2_DB_PORT
#echo $DHIS2_DB_NAME

PSQL_EXE="psql -qAtX -U $DHIS2_DB_USERNAME -d $DHIS2_DB_NAME"

$PSQL_EXE -c "SELECT description FROM constant WHERE name = '$COMMON_FUNCTIONS_SQL'" > $SQL_HOME/$COMMON_FUNCTIONS_SQL
$PSQL_EXE -c "SELECT description FROM constant WHERE name = '$MENTAL_HEALTH_SQL'" > $SQL_HOME/$MENTAL_HEALTH_SQL
$PSQL_EXE -c "SELECT description FROM constant WHERE name = '$MAIN_SQL'" > $SQL_HOME/$MAIN_SQL

$PSQL_EXE -f $SQL_HOME/$COMMON_FUNCTIONS_SQL
$PSQL_EXE -f $SQL_HOME/$MENTAL_HEALTH_SQL
$PSQL_EXE -f $SQL_HOME/$MAIN_SQL

rm $SQL_HOME/$COMMON_FUNCTIONS_SQL
rm $SQL_HOME/$MENTAL_HEALTH_SQL
rm $SQL_HOME/$MAIN_SQL
